require('dotenv').config()
const fs = require('fs')
const db = require('./db')
const start = require('./controllers/start')
const clearFile = require('./controllers/clearFile')
const upload = require('./controllers/upload')
const history = require('./controllers/history')
const callbackQuery = require('./controllers/callbackQuery')
const telegramBot = require('node-telegram-bot-api')
const bot = new telegramBot(process.env.TELEGRAM_API_TOKEN, { polling: true })
db(`mongodb+srv://${process.env.USERNAME_DB}:${encodeURI(process.env.PASSWORD_DB)}@bot.utkbgol.mongodb.net/?retryWrites=true&w=majority`, { useNewUrlParser: true, useUnifiedTopology: true })
.then(() => {
    bot.on('callback_query', callbackQuery)
    bot.onText(/\/ls/, history.bind(bot))
    bot.onText(/\/clearFile/, clearFile.bind(bot))
    bot.onText(/\/start/, start.bind(bot))
    bot.onText(/\/upload/, upload.bind(bot))
})
.catch(error => {
    console.error(error)
})